config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'places#index'
  resources :bookings, only: [:destroy, :show]
  resources :places, only: [:show, :edit, :update, :new, :create, :destroy] do
    resources :bookings, only: [:create, :new, :edit, :update]
  end
  get 'mybookings', to: "bookings#my_bookings"
  get 'myplaces', to: 'places#my_places'

  # devise_for :users
  # root to: "pages#home"
  # root to: 'places#index'
  # get "/about", to: "pages#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
require 'date'

class Booking < ApplicationRecord
  belongs_to :place
  belongs_to :user
  validates :check_in, :check_out, presence: true
  validates :check_out, comparison: { greater_than: :check_in }
  validates :check_in, comparison: { greater_than: Date.today }
end

app/models/place.rb
class Place < ApplicationRecord
  has_one_attached :photo
  has_many :bookings
  belongs_to :user
  validates :name, :address, :city, :price, presence: true
  validates :price, numericality: { only_integer: true }
  # validates :name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  alias_attribute :nation, :country
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  has_many :bookings
  has_many :places
  validates :first_name, :last_name, :phone_number, :dni, presence: true
  validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :dni, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :dni, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :dni, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    set_booking
  end

  def new
    @place = Place.find(params[:place_id])
    @user = current_user
    @booking = Booking.new
  end

  # GET
  def edit
    set_booking
    @place = Place.find(params[:place_id])
  end

  def create
    @place = Place.find(params[:place_id])
    @booking = Booking.new(booking_params)
    @booking.place = @place
    @booking.user = current_user


    if @booking.save!
      redirect_to booking_path(@booking), notice: "Booking was successfully created."
    else
      render :new, status: :unprocessable_entity # Indica el error en el formulario y hace un renderizado
    end
  end

  # PATCH/PUT
  def update
    set_booking
    if @booking.update(booking_params)
      redirect_to booking_path(@booking), notice: "This Booking was successfully updated."
    else
      render :edit, status: :unprocessable_entity # Indica el error en el formulario y hace un renderizado
    end
  end

  # DELETE
  def destroy
    set_booking
    @booking.destroy
    redirect_to place_path(@booking.place), status: :see_other, notice: "This Booking was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def booking_params
    params.require(:booking).permit(:check_in, :check_out)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  def index
    @places = Place.all
  end

  def show
    set_place
  end

  def new
    @place = Place.new
  end

  # GET
  def edit
    set_place
  end

  def create
    @place = Place.new(place_params)
    @place.user = current_user


    if @place.save!
      redirect_to place_path(@place), notice: "Place was successfully created."
    else
      render :new, status: :unprocessable_entity # Indica el error en el formulario y hace un renderizado
    end

  end

  # PATCH/PUT
  def update
    set_place
    if @place.update(place_params)
      redirect_to place_url(@place), notice: "This Place was successfully updated."
    else
      render :edit, status: :unprocessable_entity # Indica el error en el formulario y hace un renderizado
    end
  end

  # DELETE
  def destroy
    set_place
    @place.destroy
    redirect_to root_path, notice: "This Place was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_place
    @place = Place.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def place_params
    params.require(:place).permit(:name, :address, :city, :nation, :price, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    set_user
  end

  private

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container pt-5">
  <%= simple_form_for [@place, @booking] do |f| %>
    <%= f.input :check_in %>
    <%= f.input :check_out %>
    <%= f.submit "Submit booking", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<div>
  <div class="row container-half-cover justify-content-center align-items-center">

    <div class="container-half-image col-6" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://res.cloudinary.com/dr7mlnvca/image/upload/v1665257075/annie-spratt-MChSQHxGZrQ-unsplash_x3kjqj.jpg)"></div>

    <div class="p-5 col-6">
      <h4 class="py-3">Modifica tu reserva:</h4>
      <%= simple_form_for [@place, @booking] do |f| %>
        <%= f.input :check_in %>
        <%= f.input :check_out %>
        <%= button_to "Modificar Reserva", place_booking_path(@place, @booking), :method => :put, class: "btn btn-primary" %>
      <% end %>
    </div>

  </div>
</div>

app/views/bookings/new.html.erb
<div>
  <div class="row container-half-cover justify-content-center align-items-center">

    <div class="container-half-image col-6" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://res.cloudinary.com/dr7mlnvca/image/upload/v1665257075/annie-spratt-MChSQHxGZrQ-unsplash_x3kjqj.jpg)"></div>

    <div class="p-5 col-6">
      <h4 class="py-3">Reserva tu lugar de trabajo:</h4>
      <%= render 'form'%>
    </div>

  </div>
</div>

app/views/bookings/show.html.erb
<div class="card container mt-5 mb-5" style="height: 100%;">
  <div class="row g-0 d-flex flex-column mb-5">
    <div class="col-md-4 mt-3 w-100">
       <img src="<%= cl_image_path @booking.place.photo.key %>" class="card-img-top" alt="...">
    </div>
    <div class="col-md-8 mt-3 w-100">
      <div class="card-body pb-0">
        <h5 class="card-title h1 p-3"><strong>Reservacion</strong></h5>
        <p class="card-text h3 p-3">Tu reservación ha sido creada con éxito con los siguientes datos</p>
        <ul class="list-group list-group-flush">
          <li class="list-group-item h4">Check in: <%= @booking.check_in %></li>
          <li class="list-group-item h4">Check out: <%= @booking.check_out %></li>
          <li class="list-group-item h4">Lugar: <%= @booking.place.name %>, <%= @booking.place.address %></li>
        </ul>
        <div class="card-body pb-0">
          <%= link_to "Cancelar", booking_path(@booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-primary" %>
          <%= link_to 'Cambiar fechas', edit_place_booking_path(@booking.place, @booking), class:"btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkspotConJavaScript</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <div class="main">
      <%= yield %>
    </div>

    <%= render "shared/footer" %>
  </body>

</html>

app/views/pages/about.html.erb
<h1>This is our about page</h1>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/places/_form.html.erb
<%= simple_form_for(@place) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-imputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :nation %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form_actions btn btn-primary">
    <%= f.button :submit %>
  </div>
  <%= link_to 'Back to places', root_path %>
<% end %>

app/views/places/edit.html.erb
<div class="container">
  <%= render 'form'%>
  <%= link_to 'Back to place', place_path(@place) %>
</div>

app/views/places/index.html.erb
<header class="card-category bg-dark py-5" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dr7mlnvca/image/upload/v1664924276/redd-5U_28ojjgms-unsplash_xlgyco.jpg)">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">Bienvenido a WorkSpot</h1>
      <p class="lead fw-normal text-white-50 mb-0">Encuentra el lugar perfecto para trabajar</p>
      <div>
        <%= link_to 'Publica un espacio', new_place_path, class: 'p-3 m-3 btn btn-primary' %>
      </div>
    </div>
  </div>
</header>

<div class="pt-4 container">
  <% if user_signed_in? %>
    <h3 class="container">Hola <%= current_user.first_name %>!</h3>
  <% end %>
</div>

<div class="container text-center">
  <div class="row">
    <% @places.each do |place| %>
    <div class="p-4 col-6 col-md-4 col-sm-12">
      <div class="card-trip">
          <%= cl_image_tag place.photo.key %>
        <div class="card-trip-infos">
          <div>
            <h2><%= place.name %></h2>
            <p><%= place.city %>, <%= place.country %></p>
            <p><%= link_to 'Ver mas >', place_path(place) %></p>
          </div>
          <h2 class="card-trip-pricing">
            $ <%= place.price %>/dia
          </h2>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="py-5 container text-center">
  <div class="row">
    <h4>Publica un espacio y empieza a generar ingresos adicionales:</h4>
    <div>
      <%= link_to 'Publica un espacio', new_place_path, class: "p-3 m-3 btn btn-outline-primary" %>
    </div>
  </div>
</div>

app/views/places/new.html.erb
<div>
  <div class="row container-half-cover justify-content-center align-items-center">

    <div class="container-half-image col-6" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://res.cloudinary.com/dr7mlnvca/image/upload/v1665248284/olena-sergienko-dIMJWLx1YbE-unsplash_ihgybj.jpg)"></div>

    <div class="p-5 col-6">
      <h4 class="py-3">Ingresa los siguientes datos para crear un espacio de trabajo:</h4>
      <%= render 'form'%>
    </div>

  </div>
</div>

app/views/places/show.html.erb
<div class=" mx-5 mt-5 mb-5 show-place">
  <div class="container-place">
    <h1 strong center><%= @place.name %></h1>
      <div class="mt-5">
        <%= cl_image_tag @place.photo.key, crop: :fill, class:"place-image" %>
      </div>
  </div>

  <div class="container-booking">
    <blockquote class="blockquote border-start border-5 ps-3 mt-3">
      <p><%= @place.address %>, <%= @place.nation %></p>
      <figcaption class="blockquote-footer">
        <cite title="Source Title">Ubicacion</cite>
      </figcaption>
      <p>$ <%= @place.price %>/día</p>
      <figcaption class="blockquote-footer">
        <cite title="Source Title">Precio</cite>
      </figcaption>
    </blockquote>

    <ul class="inline-list">
      <% if current_user == @place.user %>
        <li>
          <a href="#" target="_blank">
            <%= link_to 'Edit', edit_place_path, class: 'btn btn-primary' %>
          </a>
        </li>
        <li>
          <a href="#" target="_blank">
            <%= link_to "Delete",
                  place_path(@place),
                  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
          </a>
        </li>
      <% end %>
      <li>
        <a href="#" target="_blank">
          <%= link_to 'Booking', new_place_booking_path(@place), class: 'btn btn-primary' %>
        </a>
      </li>
      <li>
        <a href="#" target="_blank">
          <%= link_to 'Back to places', root_path, class: 'btn btn-primary' %>
        </a>
      </li>
    </ul>
    <div class="card">
      <div class="card-header">
        Bookings
      </div>
      <ul class="list-group list-group-flush">
        <% @place.bookings.each do |booking| %>
          <li class="list-group-item">
            <h3> Ocupado de:<%= booking.check_in %>, Hasta: <%= booking.check_out %> </h3>
            <% if booking.user == current_user %>
              <%= link_to "Delete",
                  booking_path(booking),
                  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
                %>
              <div class="container m-3 border-start border-5">
                <%= link_to 'Edit', edit_place_booking_path(@place, booking), class: 'btn btn-primary' %>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer col-12">
    <div>
      <ul class="inline-list">
        <li>
          <a href="#" target="_blank">
            <i class="fab fa-linkedin-in"></i>
          </a>
        </li>
        <li>
          <a href="#" target="_blank">
            <i class="fab fa-instagram"></i>
          </a>
        </li>
        <li>
          <a href="#" target="_blank">
            <i class="fab fa-facebook"></i>
          </a>
        </li>
      </ul>
      <p>Copyright &copy; WorkSpot 2022</p>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container px-4 px-lg-5">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "http://res.cloudinary.com/dr7mlnvca/image/upload/v1664904573/xrwktcujhod100mrbezu.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Perfil", users_show_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, style:"height: 50px; width: 50px; border-radius: 50%; object-fit: cover;" %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <li style="margin-right: 20px"><p>Bienvenido a tu perfil</p></li>
            <li style="margin-right: 20px"><span>|</span></li>
            <li class="breadcrumb-item active" aria-current="page"><%= @user.first_name %> <%= @user.last_name %></li>
          </ol>
        </nav>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
          <% if @user.photo.attached? %>
            <img src="<%= cl_image_path @user.photo.key, height: 300, crop: :fill %>" alt="avatar"
              class="rounded-circle img-fluid" style="height: 60px; width: 60px; border-radius: 50%; object-fit: cover;">

          <% else %>
            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
              class="rounded-circle img-fluid" style="width: 150px;">
          <% end %>

            <h5 class="my-3"><%= @user.first_name %> <%= @user.last_name %></h5>
            <p class="text-center"><%= link_to "Editar perfil", edit_user_registration_path, class: "text-center" %></p>
            <p class="text-center"><%= link_to "Eliminar perfil", cancel_user_registration_path %></p>
            <div class="d-flex justify-content-center mb-2">
              <button type="button" class="btn btn-outline-primary ms-1">Follow</button>
              <button type="button" class="btn btn-outline-primary ms-1">Message</button>
            </div>
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
            <ul class="list-group list-group-flush rounded-3">
              <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                  <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Ganancias / Reserva</h4>
                  </div>
                <div class="card-body">
                  <h1 class="card-title pricing-card-title">$400K<small class="text-muted fw-light">/mes</small></h1>
                  <ul class="list-unstyled mt-3 mb-4">
                    <li>10 Bookings en tus coworkings</li>
                    <li>2 Bookings Activas</li>
                    <li>3 Propiedades Totales</li>
                    <li>0 Reservas Realizadas</li>
                  </ul>
                  <button type="button" class="w-100 btn btn-lg btn-outline-primary">Ver Detalles</button>
                </div>
              </div>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Nombre Completo</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.first_name %> <%= @user.last_name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.email %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Celular</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.phone_number %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">DNI</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.dni %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Acceso:</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= "Propietario" %></p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="card mb-4 mb-md-0">
              <div class="card-body">
                <p class="mb-4"><span class="text-primary font-italic me-1">Properties</span> Places</p>
                <% @user.places.each do |place| %>
                <div class="card">
                  <%= link_to  place.name, place_path(place), class:"mb-1 w-100 btn btn-lg btn-outline-primary" %>
                  <p class="mt-2 mb-1" style="font-size: .77rem; margin-left: 20px">Dirección: <%= place.address %></p>
                  <p class="mt-2 mb-1" style="font-size: .77rem; margin-left: 20px">Ciudad: <%= place.city %></p>
                  <p class="mt-2 mb-1 card-title pricing-card-title" style="margin-left: 20px">Precio: $<%= place.price %><small class="text-muted fw-light"> COP/mes</small></p>
                </div>
                <p></p>
                <% end %>
                <div class="progress rounded mb-2" style="height: 5px;">

                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card mb-4 mb-md-0">
              <div class="card-body">
                <p class="mb-4"><span class="text-primary font-italic me-1">Bookings</span> Details</p>
                <% @user.bookings.each do |booking| %>
                <div class="card">
                 <div class="card-header">
                  <p class="mb-1" style="font-size: .77rem;"><%= booking.place.name %>
                </div>
                <div class="card-body">
                  <p class="mb-1" style="font-size: .77rem;">Dirección: <%= booking.place.address %></p>
                  <p class="mb-1" style="font-size: .77rem; color: green">Fecha de Inicio:</p>
                  <p class="mb-1" style="font-style: bold;"><%= booking.check_in %></p>
                  <p class="mb-1" style="font-size: .77rem; color: green">Fecha de Salida:</p>
                  <p class="mb-1" style="font-style: bold;"><%= booking.check_out %></p>
                  <ul class="inline-list">
                    <li class="mt-2 mb-2">
                      <a href="#" target="_blank">
                        <%= link_to "Cancelar", booking_path(booking), class: 'btn btn-primary', data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                      </a>
                    </li>
                    <li class="mt-2 mb-2">
                      <a href="#" target="_blank" class=>
                        <%= link_to 'Cambiar fechas', edit_place_booking_path(booking.place, booking), class: 'btn btn-primary' %>
                      </a>
                    </li>
                  </ul>
                </div>
                <p></p>
                <% end %>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>